version: '3.8'
services:
  spring-native:
    image: ghcr.io/swissbuechi/spring-native-demo:latest-native
    #    build:
    #      context: ./
    #      dockerfile: Dockerfile-native
    container_name: spring-native
    environment:
      - test.name=peter
    healthcheck:
      test: curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1
    ports:
      - "8080:8080"
  spring-native-jre:
    image: ghcr.io/swissbuechi/spring-native-demo:latest
    #    build:
    #      context: ./
    container_name: spring-native-jre
    environment:
      - test.name=peter
    healthcheck:
      test: curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1
    ports:
      - "8081:8080"