FROM vegardit/graalvm-maven:latest-java17 as build

ADD . /app
WORKDIR /app

RUN rm -rf src/main/resources/application.properties
RUN mvn -Pnative native:compile -DskipTests=true

FROM alpine:3
LABEL maintainer="github.com/swissbuechi"
ENV TZ=Europe/Zurich
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app

RUN apk add --no-cache gcompat curl

RUN addgroup --gid 1000 -S app && adduser --uid 1000 -S app -G app
RUN chown -R app:app /app
USER app

COPY --from=build /app/target/app app
ENTRYPOINT [ "sh", "-c", "./app" ]
HEALTHCHECK CMD curl --fail --silent localhost:8080/actuator/health | grep UP || exit 1