name: Binary Artifacts native

#on: [ push ]

on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  build:
    name: graalvm ${{ matrix.version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        version: [ dev, latest ]
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        exclude:
          - os: macos-latest # remove to build macos
          - os: windows-latest # remove to build windows
          #          - os: ubuntu-latest # remove to build ubuntu
          - os: windows-latest
            version: latest
          - os: macos-latest
            version: dev
          - os: ubuntu-latest
            version: dev
        include:
          - os: ubuntu-latest
            executable-suffix: ''
          - os: macos-latest
            executable-suffix: ''
          - os: windows-latest
            executable-suffix: '.exe'

    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.version }}
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Native Binary
        run: |
          mvn -Pnative package -DskipTests=true

      - name: Upload archive
        uses: actions/upload-artifact@v2
        with:
          name: demo-${{ matrix.os }}
          path: target/demo${{ matrix.executable-suffix }}

      - name: Upload release
        if: github.event.release.tag_name
        run: gh release upload ${{ github.event.release.tag_name }} target/demo${{ matrix.executable-suffix }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}