name: Scan Docker image

on:
  workflow_dispatch:
  release:
    types: [ published ]

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  DOCKLE_HOST: "unix:///var/run/docker.sock"
  DOCKER_CONTENT_TRUST: 1

jobs:
  scan-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Scan Docker image
        uses: Azure/container-scan@v0
        with:
          image-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}